# ===============================
# App Configuration
# ===============================
spring.application.name=${SPRING_APPLICATION_NAME}

# ===============================
# Keycloak Configuration
# ===============================
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client_id=${KEYCLOAK_CLIENT_ID}
keycloak.client_secret=${KEYCLOAK_CLIENT_SECRET}
keycloak.server_url=${KEYCLOAK_SERVER_URL}


# ========================
# Ollama (TinyLlama) Config
# ========================

spring.ai.ollama.chat.model=tinyllama

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.temperature=0.7

spring.ai.ollama.chat.options.max-tokens=200


# ===============================
# Database Configuration
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

# ===============================
# Security
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

