spring.application.name=story-spark

keycloak.realm=story-spark
keycloak.client_id=admin-cli
keycloak.client_secret=7Xuel6IJmZuMV0jojB09KBqErCS5Qlih
keycloak.server_url=http://localhost:8181




spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.api-key=AIzaSyBpwx3ZyEG2m54kYM19xGpNAsbthybl8L4
spring.ai.openai.chat.options.model=gemini-2.0-flash



# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Formatting SQL
spring.jpa.properties.hibernate.format_sql=true



